apiVersion: v1
kind: Template
metadata:
  name: nginx
objects:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: nginx-passthrough-${IDENTIFIER}
  spec:
    replicas: 1
    selector:
      name: nginx-passthrough-${IDENTIFIER}
    template:
      metadata:
        labels:
          name: nginx-passthrough-${IDENTIFIER}
          test: http
      spec:
        containers:
        - image: ${HTTP_TEST_SERVER_CONTAINER_IMAGE}
          imagePullPolicy: IfNotPresent
          name: nginx-passthrough
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          securityContext:
            capabilities:
              drop:
              - KILL
              - MKNOD
              - SETGID
              - SETUID
              - SYS_CHROOT
            privileged: false
        restartPolicy: Always
- apiVersion: v1
  kind: Route
  metadata:
    name: nginx-passthrough-${IDENTIFIER}
  spec:
    host: ${APPLICATION_DOMAIN}
    tls:
      termination: passthrough
    to:
      kind: Service
      name: nginx-passthrough-${IDENTIFIER}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    labels:
      name: nginx-passthrough
    name: nginx-passthrough-${IDENTIFIER}
  spec:
    ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      name: nginx-passthrough-${IDENTIFIER}
    type: NodePort
parameters:
- description: The exposed hostname that will route to the nginx-* service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
  value: ''
- description: Number to append to the name of resources
  name: IDENTIFIER
  value: '1'
- description: HTTP server container image
  name: HTTP_TEST_SERVER_CONTAINER_IMAGE
  value: 'quay.io/openshift-scale/nginx'
