# e2e specific vars
provider: local
# Cluster loader specific part
ClusterLoader:
  cleanup: true
  projects:
    - num: 1
      ifexists: delete
      basename: centos-stress
      tuning: default
      configmaps:
        - wlg-targets: routes.txt
      secrets:
        - wlg-ssh-key: /root/.ssh/id_rsa
      templates:
        - num: 1
          file: quickstarts/stress/stress-pod.yaml
          parameters:
            - WLG_IMAGE:                # Workload generator image
            - RUN: "mb"			# which app to execute inside WLG pod
            - RUN_TIME:  		# benchmark run-time in seconds
            - GUN:      		# host for synchronisation
            - RESULTS_DIR:		# fetch RESULTS_DIR from the environment
            - PLACEMENT: "test"		# placement of the WLG pods based on a node's label
            - SERVER_RESULTS:   	# ssh server for collecting results
            - SERVER_RESULTS_DIR: 	# server directory for collecting results
            - MB_DELAY: 		# maximum delay between client requests in ms
            - MB_TARGETS: 		# extended RE (egrep) to filter target routes
            - MB_CONNS_PER_TARGET: 	# how many connections per target route
            - MB_METHOD: 		# HTTP method (GET by default)
            - MB_REQUEST_BODY_SIZE:	# body length of POST requests in characters
            - MB_KA_REQUESTS: 		# how many HTTP keep-alive requests to send before sending "Connection: close".
            - MB_TLS_SESSION_REUSE: 	# use TLS session reuse [yn]
            - MB_RAMP_UP: 0		# thread ramp-up time in seconds
            - URL_PATH: 		# target path for HTTP(S) requests
#          sync:
#            server: 
#              enabled: true			# enable/start HTTP server for synchronization
#              port: 9090			# HTTP server endpoint port
#            running: true			# wait for pods with labels matching selectors below to go into Running state
#            succeeded: true			# wait for pods with labels matching selectors below to go into Completed state
#            selectors:				# selectors to match pods in Running/Completed states
#              run: "centos-stress"
#            timeout: 0				# synchronization timeout to wait for running/finished pods
  tuningsets: 
    - name: default
      pods:
        stepping:
          stepsize: 5
          pause: 3      # seconds
          timeout: 300  # seconds
        ratelimit:
          delay: 100    # milliseconds
      templates:
        stepping: 
          stepsize: 1
          pause: 0     # seconds
          timeout: 120  # seconds
        ratelimit: 
          delay: 200    # milliseconds
  sync:
    server:
      enabled: true			# enable/start HTTP server for synchronization
      port: 0				# HTTP server endpoint port
    running: true			# wait for pods with labels matching selectors below to go into Running state
    succeeded: true			# wait for pods with labels matching selectors below to go into Completed state
    selectors:				# selectors to match pods in Running/Completed states
      run: "centos-stress"
    timeout: 0s				# synchronization timeout to wait for running/finished pods (for non 0 values use units: [ns|us|ms|s|m|h])
